{\aicontent
\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{The cic tools}\index{cicsim@cicsim}\index{ciccreator@ciccreator}\index{cicpy@cicpy}\index{cicconf@cicconf}\index{cicwave@cicwave}\index{cictikz@cictikz}\index{ngspice@ngspice}\index{corners@Corners}\index{monte carlo@Monte carlo}\index{layout compilation@Layout compilation}\index{reproducibility@Reproducibility}
\input{the_cic_tools_fiximg.tex}

}

