\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{Diodes}\index{silicon@Silicon}\index{intrinsic carriers@Intrinsic carriers}\index{density of states@Density of States}\index{fermi-dirac@Fermi-Dirac}\index{doping@Doping}\index{pn junction@PN Junction}\index{built-in voltage@Built-in voltage}\index{diode equation@Diode equation}\index{temperature@Temperature}\index{leakage@Leakage}
\input{diodes_fiximg.tex}

