\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{Switched-Capacitor Circuits}\index{sc dac@SC DAC}\index{sc fund@SC FUND}\index{dt@DT}\index{alias@Alias}\index{subsample@Subsample}\index{z domain@Z Domain}\index{fir@FIR}\index{iir@IIR}\index{sc mdac@SC MDAC}\index{sc int@SC INT}\index{switch@Switch}\index{non-overlap@Non-Overlap}\index{vbe sc@VBE SC}\index{nyquist@Nyquist}
\input{switched-capacitor_circuits_fiximg.tex}

