\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{Voltage regulation}\index{battery@Battery}\index{vreg@Vreg}\index{ldop@LDOP}\index{ldon@LDON}\index{flipped voltage follower@Flipped voltage follower}\index{buck@Buck}\index{boost@Boost}\index{load@Load}\index{line@Line}\index{psrr@PSRR}\index{max c@MAX C}\index{quiescent@Quiescent}\index{settling@Settling}\index{efficiency@Efficiency}\index{pwm@PWM}\index{pfm@PFM}
\input{voltage_regulation_fiximg.tex}

