\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{Equations}\index{reference@Reference}\index{physics@Physics}\index{semiconductors@Semiconductors}\index{diode@Diode}\index{mosfet@MOSFET}\index{noise@Noise}\index{circuits@Circuits}\index{references@References}\index{filters@Filters}\index{switched capacitor@Switched capacitor}\index{data converters@Data converters}\index{regulators@Regulators}\index{pll@PLL}\index{oscillators@Oscillators}\index{radio@Radio}
\input{equations_fiximg.tex}

