\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{MOSFETs}\index{field effect@Field effect}\index{weak inversion@Weak inversion}\index{strong inversion@Strong inversion}\index{threshold@Threshold}\index{gm@gm}\index{gds@gds}\index{intrinsic gain@Intrinsic gain}\index{capacitances@Capacitances}\index{miller@Miller}\index{gm/id@gm/ID}\index{velocity saturation@Velocity saturation}\index{dibl@DIBL}\index{wpe@WPE}\index{hci@HCI}\index{variability@Variability}\index{pelgrom@Pelgrom}\index{noise@Noise}
\input{mosfets_fiximg.tex}

