{\aicontent
\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{Fields}\index{maxwell@Maxwell}\index{current loops@Current loops}\index{displacement current@Displacement current}\index{capacitance@Capacitance}\index{inductance@Inductance}\index{faraday@Faraday}\index{return path@Return path}\index{near field@Near field}\index{far field@Far field}\index{antenna@Antenna}\index{radiation@Radiation}
\input{fields_fiximg.tex}

}

