\setchapterstyle{kao}
\setchapterpreamble[u]{\margintoc}
\chapter{OTAs}\index{ota@OTA}\index{headroom@Headroom}\index{five transistor@Five transistor}\index{current mirror ota@Current Mirror OTA}\index{two-stage@Two-Stage}\index{miller compensation@Miller compensation}\index{folded cascode@Folded cascode}\index{inverter-based@Inverter-Based}\index{nauta@Nauta}\index{cmfb@CMFB}\index{bias@Bias}\index{op amp@Op amp}\index{dynamic amplifiers@Dynamic amplifiers}\index{verification@Verification}
\input{otas_fiximg.tex}

