

figs:
	cat dig_des.dot | dot -Tsvg  > ../media/dig_des.svg
	cat dig_des_lr.dot | dot -Tsvg  > ../media/dig_des_lr.svg
	svg2pdf ../media/dig_des.svg ../media/dig_des.pdf
	svg2pdf ../media/dig_des_lr.svg ../media/dig_des_lr.pdf
