#!/usr/bin/env python3
"""Written descriptions of the figures, for the plain-text book.

A language model reading the book cannot see media/*_tikz.svg. The text
edition (see py/mkllms.py) replaces every figure with prose saying what
the circuit is and what it does, and this module is where that prose is
looked up.

Descriptions are keyed by figure, not by lecture, so the ~70 figures used
in more than one lecture are described once. The key is the media stem
with the generated _tikz suffix removed, keeping any subdirectory:

    ../media/l3_sources_tikz.pdf  ->  l3_sources
    ../media/l13/pills_tikz.svg   ->  l13/pills
    ../media/cjm.png              ->  cjm

Lookup order for a key:

  1. tikz/desc/<key>.md, the authored description.
  2. The header comment of tikz/<key>.tex. tikz/STYLE.md requires every
     figure to open with a comment saying what it shows and why, so this
     is a real fallback rather than a placeholder.
  3. Nothing. The caller emits the caption alone; py/check.py counts it.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESC = os.path.join(ROOT, "tikz", "desc")
TIKZ = os.path.join(ROOT, "tikz")

#- Trailing boilerplate in a generated figure's header: build
#  instructions for whoever edits it, not a description of what it shows.
GENERATED_NOTE = re.compile(
    r"\s*Generated by py/tikzplot\.py\..*", re.S)


def key(src):
    """Description key for an image reference as it appears in a lecture."""
    if re.search(r"^\s*https?://", src):
        return None
    stem = os.path.splitext(src)[0]
    #- Everything up to and including media/ is layout, not identity:
    #  the same figure is reached as ../media/x, media/x and ./media/x.
    m = re.search(r"(?:^|/)media/(.+)$", stem)
    if not m:
        return None
    return re.sub(r"_tikz$", "", m.group(1))


def figure_id(src):
    """The name the text edition prints for a figure, matching the file."""
    stem = os.path.splitext(os.path.basename(src))[0]
    return stem


def _authored(k):
    path = os.path.join(DESC, k + ".md")
    if not os.path.exists(path):
        return None
    with open(path) as fi:
        text = fi.read().strip()
    return text or None


def _header_comment(k):
    """The leading % comment block of tikz/<k>.tex, as prose."""
    path = os.path.join(TIKZ, k + ".tex")
    if not os.path.exists(path):
        return None

    lines = []
    started = False
    with open(path) as fi:
        for line in fi:
            line = line.rstrip("\n")
            #- Only the block above the drawing describes the figure.
            #  Past \begin the comments are notes on coordinates, and
            #  "Layout constants" is not a description of anything.
            if re.match(r"^\s*\\begin\{", line):
                break
            if re.match(r"^\s*%", line):
                started = True
                lines.append(re.sub(r"^\s*%\s?", "", line))
                continue
            if not line.strip():
                #- A blank line inside the block is a paragraph break; a
                #  blank line before it is just the gap under \input.
                if started:
                    lines.append("")
                continue
            if started:
                break

    text = "\n".join(lines).strip()
    text = GENERATED_NOTE.sub("", text).strip()
    #- Rewrap: the comment is hard-wrapped to the TeX file's margin, and
    #  those line breaks mean nothing in the output.
    text = re.sub(r"(?<!\n)\n(?!\n)", " ", text)
    text = re.sub(r"[ \t]+", " ", text)
    return text or None


def description(src):
    """Written description for an image reference, or None if we have none."""
    k = key(src)
    if k is None:
        return None
    return _authored(k) or _header_comment(k)


