#!/usr/bin/env python3
"""Generate tikz/jnw_sym_lib.tex from the JNW xschem symbol libraries.

The tutorial chapter walks a reader through placing particular symbols
in xschem. Redrawing those symbols by hand would mean the book and the
tool slowly disagree, so the figures use the symbols themselves,
converted by cictikz.

The generated file is committed, like the simulation data under
ex/data: building the book must not require the IP repositories to be
checked out. Regenerate with `make symlib` when a symbol changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "cictikz" / "src"))

# Where the symbol libraries live. Only needed to regenerate.
SEARCH = [
    Path.home() / "pro" / "jnw-tt-2025" / "ip",
    Path.home() / "data" / "2023" / "aicex" / "ip",
]

# symbol stem -> macro name
# Macro names are letters only, because TeX control sequences are.
WANTED = {
    "JNWATR_NCH_4C5F0": "jnwNchFiveF",
    "JNWATR_PCH_4C5F0": "jnwPchFiveF",
}

OUT = REPO / "tikz" / "jnw_sym_lib.tex"

HEADER = """% Generated by py/gen_symlib.py from the JNW xschem symbol libraries.
% Do not edit: change the symbol and run `make symlib`.
%
% These are the symbols a reader places in xschem during the tutorial,
% converted rather than redrawn so the book and the tool cannot drift
% apart. Each macro is a path fragment starting at the current point and
% exporting its pins as coordinates: (name_g), (name_d), (name_s),
% (name_b).
"""


def find(stem: str) -> Path | None:
    for root in SEARCH:
        if not root.is_dir():
            continue
        for path in root.rglob(f"{stem}.sym"):
            return path
    return None


def main() -> int:
    from cictikz.readers.xschem_sym import convert

    chunks, missing = [HEADER], []
    for stem, macro in WANTED.items():
        path = find(stem)
        if path is None:
            missing.append(stem)
            continue
        chunks.append(convert(path, macro=macro))
    if missing:
        print(f"symbols not found: {', '.join(missing)}", file=sys.stderr)
        print(f"looked under: {', '.join(str(p) for p in SEARCH)}", file=sys.stderr)
        if len(missing) == len(WANTED):
            return 1
    OUT.write_text("\n\n".join(chunks) + "\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(WANTED) - len(missing)} symbols)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
